# Generated by Django 5.0.6 on 2024-06-18 04:27

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'verbose_name': 'iva',
                'verbose_name_plural': 'iva',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.CharField(max_length=255, unique=True)),
                ('imagen', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[100, 100], upload_to='productos')),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('porcion', models.DecimalField(decimal_places=2, default=1, max_digits=20)),
                ('unidad', models.CharField(choices=[('Pieza', 'Pieza'), ('Kg', 'Kg'), ('gramos', 'gramos'), ('Lt', 'Lt'), ('Metro', 'Metro'), ('Caja', 'Caja'), ('Onza', 'Onza'), ('Charola', 'Charola'), ('Otro', 'Otro')], default='Pieza', max_length=255)),
                ('unidad_venta', models.CharField(choices=[('Pieza', 'Pieza'), ('Kg', 'Kg'), ('gramos', 'gramos'), ('Lt', 'Lt'), ('Metro', 'Metro'), ('Caja', 'Caja'), ('Onza', 'Onza'), ('Charola', 'Charola'), ('Otro', 'Otro')], default='Pieza', max_length=255)),
                ('servicio', models.BooleanField(default=False)),
                ('barcode', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'order_with_respect_to': 'descripcion',
            },
        ),
    ]
